/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockToken__factory } from "./MockToken__factory";
export { Staking__factory } from "./Staking__factory";
