/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stakingSol from "./Staking.sol";
export type { stakingSol };
export type { MockToken } from "./MockToken";
export * as factories from "./factories";
export { MockToken__factory } from "./factories/MockToken__factory";
export type { IERC20 } from "./Staking.sol/IERC20";
export { IERC20__factory } from "./factories/Staking.sol/IERC20__factory";
export type { Staking } from "./Staking.sol/Staking";
export { Staking__factory } from "./factories/Staking.sol/Staking__factory";
